name: Docker Hub Image Sync

on:
  push:
    paths:
      - 'images.txt'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Aliyun Registry
      run: |
        # 已经替换为你的广州个人版域名
        echo "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}" | docker login crpi-4hr249qoofi8wkbd.cn-guangzhou.personal.cr.aliyuncs.com -u "${{ secrets.ALIYUN_REGISTRY_USER }}" --password-stdin

    - name: Read and Sync Images
      run: |
        if [ ! -f images.txt ]; then
          echo "images.txt 不存在，请先创建该文件！"
          exit 1
        fi
        
        while IFS= read -r image || [ -n "$image" ]; do
          [[ -z "$image" || "$image" =~ ^# ]] && continue
          
          echo "----------------------------------------"
          echo "开始处理镜像: $image"
          echo "----------------------------------------"
          
          # 1. 从 Docker Hub 境外拉取镜像
          docker pull "$image"
          
          # 2. 清洗镜像名称
          if [[ "$image" != */* ]]; then
             clean_image="library_${image}"
          else
             clean_image=$(echo "$image" | tr '/' '_')
          fi
          
          repo_and_tag=$(echo "$image" | sed 's/:/ /')
          read -r raw_repo raw_tag <<< "$repo_and_tag"
          [ -z "$raw_tag" ] && raw_tag="latest"
          
          clean_repo=$(echo "$raw_repo" | tr '/' '_')
          
          # 已经将推送目标地址修改为你的广州域名
          TARGET_IMAGE="://aliyuncs.com{{ secrets.ALIYUN_NAME_SPACE }}/${clean_repo}:${raw_tag}"
          
          # 3. 打新标签并推送到阿里云
          docker tag "$image" "$TARGET_IMAGE"
          docker push "$TARGET_IMAGE"
          
          echo "同步成功！国内拉取命令："
          echo "docker pull $TARGET_IMAGE"
        done < images.txt
